# Site settings
title: Guxi11
email: guxi11@isanbel.com
description: >- # this means to ignore newlines until "baseurl:"
  Blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme settings
skin: default # default

highlighter: rouge

# Markdown settings
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

atina:
  date_format: "%B %-d, %Y"

  social_links:
    github:  hbhde
